/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Applicant;

import controller.Applicant;
import controller.Disbursement;
import static controller.HELPAidConsole.loginUser;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class ApplicantPage extends javax.swing.JFrame {
      Applicant applicant = (Applicant) loginUser; //downcasting loginUser
      ArrayList<Disbursement> disbursement = applicant.getDisbursements(); // mengambil disbursement dari applicant
      DefaultListModel listModel = new DefaultListModel(); // membuat listmodel
    /**
     * Creates new form ApplicantPage
     */
    public ApplicantPage() {
        initComponents();
        applicantWelcomePageLabel.setText("Welcome, " + applicant.getFullname()); // set label di welcoming page
        LoadDataDisbursement(); // load data disbursement
        disbursementList.setModel(listModel);
        applicantCashAmountLabelToFill.setText("");
        applicantDisbursementDateLabelToFill.setText("");
        applicantGoodDisbursedLabelToFill.setText("");
    }
    
    public void LoadDataDisbursement(){
        listModel.removeAllElements();
        for (int i = 0; i < disbursement.size(); i++) {
            listModel.addElement(disbursement.get(i).getDisbursmentID());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applicantTabbedPane = new javax.swing.JTabbedPane();
        welcomePagePanel = new javax.swing.JPanel();
        applicantWelcomePageLabel = new javax.swing.JLabel();
        viewDisbursementTabbedPaneButton = new javax.swing.JButton();
        viewDisbursementPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        disbursementList = new javax.swing.JList<>();
        viewDisbursementLabel = new javax.swing.JLabel();
        applicantDisbursementDateLabel = new javax.swing.JLabel();
        applicantCashAmountLabel = new javax.swing.JLabel();
        applicantGoodDisbursedLabel = new javax.swing.JLabel();
        seeAppealButton = new javax.swing.JButton();
        seeApplicantButton = new javax.swing.JButton();
        applicantDisbursementDateLabelToFill = new javax.swing.JLabel();
        applicantCashAmountLabelToFill = new javax.swing.JLabel();
        applicantGoodDisbursedLabelToFill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        applicantWelcomePageLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        applicantWelcomePageLabel.setText("Welcome Page");

        viewDisbursementTabbedPaneButton.setText("View Disbursement");
        viewDisbursementTabbedPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDisbursementTabbedPaneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout welcomePagePanelLayout = new javax.swing.GroupLayout(welcomePagePanel);
        welcomePagePanel.setLayout(welcomePagePanelLayout);
        welcomePagePanelLayout.setHorizontalGroup(
            welcomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePagePanelLayout.createSequentialGroup()
                .addGroup(welcomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomePagePanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(viewDisbursementTabbedPaneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcomePagePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(applicantWelcomePageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        welcomePagePanelLayout.setVerticalGroup(
            welcomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePagePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(applicantWelcomePageLabel)
                .addGap(70, 70, 70)
                .addComponent(viewDisbursementTabbedPaneButton)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        applicantTabbedPane.addTab("Welcome Page", welcomePagePanel);

        disbursementList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        disbursementList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disbursementListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(disbursementList);

        viewDisbursementLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewDisbursementLabel.setText("View Disbursement");

        applicantDisbursementDateLabel.setText("Disbursement Date :");

        applicantCashAmountLabel.setText("Cash Amount           :");

        applicantGoodDisbursedLabel.setText("Good Disbursed      :");

        seeAppealButton.setText("See Appeal !");
        seeAppealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAppealButtonActionPerformed(evt);
            }
        });

        seeApplicantButton.setText("See Applicant !");
        seeApplicantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeApplicantButtonActionPerformed(evt);
            }
        });

        applicantDisbursementDateLabelToFill.setText("jLabel4");

        applicantCashAmountLabelToFill.setText("jLabel5");

        applicantGoodDisbursedLabelToFill.setText("jLabel6");

        javax.swing.GroupLayout viewDisbursementPanelLayout = new javax.swing.GroupLayout(viewDisbursementPanel);
        viewDisbursementPanel.setLayout(viewDisbursementPanelLayout);
        viewDisbursementPanelLayout.setHorizontalGroup(
            viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDisbursementPanelLayout.createSequentialGroup()
                .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewDisbursementPanelLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(viewDisbursementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewDisbursementPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewDisbursementPanelLayout.createSequentialGroup()
                                .addComponent(seeAppealButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seeApplicantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewDisbursementPanelLayout.createSequentialGroup()
                                .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(applicantDisbursementDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(applicantCashAmountLabel)
                                    .addComponent(applicantGoodDisbursedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(applicantGoodDisbursedLabelToFill, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(applicantDisbursementDateLabelToFill, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                        .addComponent(applicantCashAmountLabelToFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(36, 36, 36))
        );
        viewDisbursementPanelLayout.setVerticalGroup(
            viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDisbursementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewDisbursementLabel)
                .addGap(33, 33, 33)
                .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewDisbursementPanelLayout.createSequentialGroup()
                        .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(applicantDisbursementDateLabel)
                            .addComponent(applicantDisbursementDateLabelToFill))
                        .addGap(28, 28, 28)
                        .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(applicantCashAmountLabel)
                            .addComponent(applicantCashAmountLabelToFill))
                        .addGap(26, 26, 26)
                        .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(applicantGoodDisbursedLabel)
                            .addComponent(applicantGoodDisbursedLabelToFill))
                        .addGap(31, 31, 31)
                        .addGroup(viewDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seeAppealButton)
                            .addComponent(seeApplicantButton))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        applicantTabbedPane.addTab("View Disbursement", viewDisbursementPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(applicantTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(applicantTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewDisbursementTabbedPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDisbursementTabbedPaneButtonActionPerformed
        // TODO add your handling code here:
         int selectedIndex = applicantTabbedPane.getSelectedIndex();
         int newIndex = (selectedIndex + 1) % applicantTabbedPane.getTabCount(); // Switch to the next tab in a circular manner
          applicantTabbedPane.setSelectedIndex(newIndex); 
    }//GEN-LAST:event_viewDisbursementTabbedPaneButtonActionPerformed

    private void disbursementListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disbursementListMouseClicked
        // TODO add your handling code here:
        String cashAmountString = Double.toString(disbursement.get(disbursementList.getSelectedIndex()).getCashAmount());
        String goodDisbursedString = Double.toString(disbursement.get(disbursementList.getSelectedIndex()).getGoodsDisbursed());
        String disbursementDateString = disbursement.get(disbursementList.getSelectedIndex()).getDisbursementDate().toString();
        applicantCashAmountLabelToFill.setText(cashAmountString);
        applicantDisbursementDateLabelToFill.setText(disbursementDateString);
        applicantGoodDisbursedLabelToFill.setText(goodDisbursedString);
    }//GEN-LAST:event_disbursementListMouseClicked

    private void seeAppealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAppealButtonActionPerformed
        // TODO add your handling code here:
        String message = disbursement.get(disbursementList.getSelectedIndex()).getAppeal().toString();
         JOptionPane.showMessageDialog(null, message, "Appeal Details", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_seeAppealButtonActionPerformed

    private void seeApplicantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeApplicantButtonActionPerformed
        // TODO add your handling code here:
        String message = disbursement.get(disbursementList.getSelectedIndex()).getApplicant().toString();
          JOptionPane.showMessageDialog(null, message, "Applicant Details", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_seeApplicantButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicantPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicantCashAmountLabel;
    private javax.swing.JLabel applicantCashAmountLabelToFill;
    private javax.swing.JLabel applicantDisbursementDateLabel;
    private javax.swing.JLabel applicantDisbursementDateLabelToFill;
    private javax.swing.JLabel applicantGoodDisbursedLabel;
    private javax.swing.JLabel applicantGoodDisbursedLabelToFill;
    private javax.swing.JTabbedPane applicantTabbedPane;
    private javax.swing.JLabel applicantWelcomePageLabel;
    private javax.swing.JList<String> disbursementList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton seeAppealButton;
    private javax.swing.JButton seeApplicantButton;
    private javax.swing.JLabel viewDisbursementLabel;
    private javax.swing.JPanel viewDisbursementPanel;
    private javax.swing.JButton viewDisbursementTabbedPaneButton;
    private javax.swing.JPanel welcomePagePanel;
    // End of variables declaration//GEN-END:variables
}
