/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.OrganizationalRep;

import controller.Appeal;
import controller.Applicant;
import controller.Contribution;
import controller.HELPAidConsole;
import static controller.HELPAidConsole.loginUser;
import controller.Organization;
import controller.OrganizationRep;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class OrganizationalRepresentativePage extends javax.swing.JFrame {
    // Assuming 'loginUser' is of type OrganizationRep, cast it to OrganizationRep.
OrganizationRep orgRep = (OrganizationRep) loginUser;

// Retrieve the organization associated with the logged-in organization representative.
Organization organization = orgRep.getOrganization();

// Get the list of appeals associated with the organization.
ArrayList<Appeal> appeals = organization.getAppeals();

// Create a DefaultListModel to hold appeal-related data.
DefaultListModel listModelAppeal = new DefaultListModel();

// Create a DefaultListModel to hold contribution-related data.
DefaultListModel listModelContribution = new DefaultListModel();

// Create a DefaultListModel to hold applicant-related data.
DefaultListModel listModelApplicant = new DefaultListModel();

    
    /**
     * Creates new form OrganizationalRepresentativePage
     */
// Constructor for the OrganizationalRepresentativePage class.
public OrganizationalRepresentativePage() {
    // Initialize components for the GUI.
    initComponents();

    // Set the welcome label to display the organization representative's information.
    orgRepWelcomePageLabel.setText("Welcome, " + orgRep.getFullname() + 
        " [" + orgRep.getJobTitle() + " of " + 
        orgRep.getOrganization().getOrgName() + "]");

    // Set the label for current appeals with the organization name.
    currentAppealDisbursementLabel.setText("Current Appeals of '" + organization.getOrgName() + "':");

    // Set the model for the appealListDisbursement to listModelAppeal.
    appealListDisbursement.setModel(listModelAppeal);

    // Set the model for the appealListContribution to listModelAppeal.
    appealListContribution.setModel(listModelAppeal);

    // Set the model for the contributionListDisbursement to listModelContribution.
    contributionListDisbursement.setModel(listModelContribution);

    // Set the model for the applicantListDisbursement to listModelApplicant.
    applicantListDisbursement.setModel(listModelApplicant);

    // Create a formatted string containing information about the organization.
    String infoOrg = String.format("<html><div style='text-align: right;'>%s <br> [%s] <br> at %s</div></html>",
            organization.getOrgName(), organization.getOrgID(), organization.getAddress());

    // Set the label to display the formatted organization information.
    infoOrganizationRegisterApplicantLabel.setText(infoOrg);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        organizeAidAppealLabel1 = new javax.swing.JLabel();
        organizationRepTabbedPane = new javax.swing.JTabbedPane();
        welcomePagePanel = new javax.swing.JPanel();
        orgRepWelcomePageLabel = new javax.swing.JLabel();
        organizeAidAppealTabbedPaneButton = new javax.swing.JButton();
        recordContributtionTabbedPaneButton = new javax.swing.JButton();
        recordDisbursementTabbedPaneButton = new javax.swing.JButton();
        registerApplicantTabbedPaneButton = new javax.swing.JButton();
        organizeAidAppealPanel = new javax.swing.JPanel();
        appealFromDateLabel = new javax.swing.JLabel();
        appealToDateLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        appealDescriptionLabel = new javax.swing.JLabel();
        organizeAidAppealLabel = new javax.swing.JLabel();
        organizeAidAppealButton = new javax.swing.JButton();
        fromDateTextField = new javax.swing.JTextField();
        toDateTextField = new javax.swing.JTextField();
        recordContributionPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        appealListContribution = new javax.swing.JList<>();
        recordContributionLabel = new javax.swing.JLabel();
        contributionTypeComboBox = new javax.swing.JComboBox<>();
        contributionTypeLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        paymentChannelTextField = new javax.swing.JTextField();
        paymentChannelLabel = new javax.swing.JLabel();
        referenceNoTextField = new javax.swing.JTextField();
        referenceNoLabel = new javax.swing.JLabel();
        estimatedValueLabel = new javax.swing.JLabel();
        estimatedValueTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        submitContributionButton = new javax.swing.JButton();
        currentAppealDisbursementLabel1 = new javax.swing.JLabel();
        recordDisbursementPanel = new javax.swing.JPanel();
        currentAppealDisbursementLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        appealListDisbursement = new javax.swing.JList<>();
        recordDisbursementLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        contributionListDisbursement = new javax.swing.JList<>();
        listContributionLabel = new javax.swing.JLabel();
        cashAmountTextField = new javax.swing.JTextField();
        goodDisbursedTextField = new javax.swing.JTextField();
        cashAmountLabel = new javax.swing.JLabel();
        goodDisbursedLabel = new javax.swing.JLabel();
        recordDisbursementButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        applicantListDisbursement = new javax.swing.JList<>();
        listContributionLabel1 = new javax.swing.JLabel();
        listOfAppealLabel = new javax.swing.JLabel();
        registerApplicantPanel = new javax.swing.JPanel();
        applicantFullnameTextField = new javax.swing.JTextField();
        applicantFullNameLabel = new javax.swing.JLabel();
        applicantEmailLabel = new javax.swing.JLabel();
        applicantEmailTextField = new javax.swing.JTextField();
        applicantMobileNoLabel = new javax.swing.JLabel();
        applicantMobileNoTextField = new javax.swing.JTextField();
        registerApplicantLabel = new javax.swing.JLabel();
        applicantAddressLabel = new javax.swing.JLabel();
        applicantAddressTextField = new javax.swing.JTextField();
        applicantHouseHoldIncomeLabel = new javax.swing.JLabel();
        applicantHouseholdTextField = new javax.swing.JTextField();
        registerApplicantButton = new javax.swing.JButton();
        titleOrganizationRegisterApplicantLabel = new javax.swing.JLabel();
        infoOrganizationRegisterApplicantLabel = new javax.swing.JLabel();

        organizeAidAppealLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        organizeAidAppealLabel1.setText("Organize Aid Appeal");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orgRepWelcomePageLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        orgRepWelcomePageLabel.setText("Welcome Page");

        organizeAidAppealTabbedPaneButton.setText("Organize Aid Appeal");
        organizeAidAppealTabbedPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizeAidAppealTabbedPaneButtonActionPerformed(evt);
            }
        });

        recordContributtionTabbedPaneButton.setText("Record Contribution");
        recordContributtionTabbedPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordContributtionTabbedPaneButtonActionPerformed(evt);
            }
        });

        recordDisbursementTabbedPaneButton.setText("Record Disbursement");
        recordDisbursementTabbedPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordDisbursementTabbedPaneButtonActionPerformed(evt);
            }
        });

        registerApplicantTabbedPaneButton.setText("Register Applicant");
        registerApplicantTabbedPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerApplicantTabbedPaneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout welcomePagePanelLayout = new javax.swing.GroupLayout(welcomePagePanel);
        welcomePagePanel.setLayout(welcomePagePanelLayout);
        welcomePagePanelLayout.setHorizontalGroup(
            welcomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePagePanelLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(welcomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(organizeAidAppealTabbedPaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recordContributtionTabbedPaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recordDisbursementTabbedPaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerApplicantTabbedPaneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(welcomePagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orgRepWelcomePageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        welcomePagePanelLayout.setVerticalGroup(
            welcomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePagePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(orgRepWelcomePageLabel)
                .addGap(18, 18, 18)
                .addComponent(organizeAidAppealTabbedPaneButton)
                .addGap(18, 18, 18)
                .addComponent(recordContributtionTabbedPaneButton)
                .addGap(18, 18, 18)
                .addComponent(recordDisbursementTabbedPaneButton)
                .addGap(18, 18, 18)
                .addComponent(registerApplicantTabbedPaneButton)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        organizationRepTabbedPane.addTab("Welcome page", welcomePagePanel);

        appealFromDateLabel.setText("From Date :");

        appealToDateLabel.setText("To Date :");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        appealDescriptionLabel.setText("Description :");

        organizeAidAppealLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        organizeAidAppealLabel.setText("Organize Aid Appeal");

        organizeAidAppealButton.setText("organize !");
        organizeAidAppealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizeAidAppealButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout organizeAidAppealPanelLayout = new javax.swing.GroupLayout(organizeAidAppealPanel);
        organizeAidAppealPanel.setLayout(organizeAidAppealPanelLayout);
        organizeAidAppealPanelLayout.setHorizontalGroup(
            organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizeAidAppealPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(organizeAidAppealLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(organizeAidAppealButton)
                        .addGroup(organizeAidAppealPanelLayout.createSequentialGroup()
                            .addGroup(organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(appealFromDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(appealDescriptionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(appealToDateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(36, 36, 36)
                            .addGroup(organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                .addComponent(toDateTextField)
                                .addComponent(fromDateTextField)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        organizeAidAppealPanelLayout.setVerticalGroup(
            organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, organizeAidAppealPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(organizeAidAppealLabel)
                .addGap(18, 18, 18)
                .addGroup(organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appealFromDateLabel)
                    .addComponent(fromDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appealToDateLabel)
                    .addComponent(toDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(organizeAidAppealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appealDescriptionLabel))
                .addGap(18, 18, 18)
                .addComponent(organizeAidAppealButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        organizationRepTabbedPane.addTab("Organize Aid Appeal", organizeAidAppealPanel);

        appealListContribution.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(appealListContribution);

        recordContributionLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        recordContributionLabel.setText("Record Contribution");

        contributionTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Good" }));

        contributionTypeLabel.setText("Contribution Type :");

        jLabel1.setText("Amount :");

        paymentChannelTextField.setToolTipText("");

        paymentChannelLabel.setText("Payment Channel :");

        referenceNoLabel.setText("Reference No :");

        estimatedValueLabel.setText("Estimated Value :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jLabel2.setText("Description :");

        submitContributionButton.setText("Submit !");
        submitContributionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitContributionButtonActionPerformed(evt);
            }
        });

        currentAppealDisbursementLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        currentAppealDisbursementLabel1.setText("Current Appeals of");

        javax.swing.GroupLayout recordContributionPanelLayout = new javax.swing.GroupLayout(recordContributionPanel);
        recordContributionPanel.setLayout(recordContributionPanelLayout);
        recordContributionPanelLayout.setHorizontalGroup(
            recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordContributionPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordContributionPanelLayout.createSequentialGroup()
                        .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(recordContributionPanelLayout.createSequentialGroup()
                                .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentAppealDisbursementLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contributionTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paymentChannelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(referenceNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estimatedValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordContributionPanelLayout.createSequentialGroup()
                                .addComponent(submitContributionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)))
                        .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contributionTypeComboBox, 0, 141, Short.MAX_VALUE)
                            .addComponent(amountTextField)
                            .addComponent(paymentChannelTextField)
                            .addComponent(referenceNoTextField)
                            .addComponent(estimatedValueTextField)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(recordContributionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        recordContributionPanelLayout.setVerticalGroup(
            recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordContributionPanelLayout.createSequentialGroup()
                .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordContributionPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contributionTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contributionTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentChannelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentChannelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(referenceNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(referenceNoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estimatedValueLabel)
                            .addComponent(estimatedValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recordContributionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(recordContributionLabel)
                        .addGap(5, 5, 5)
                        .addComponent(currentAppealDisbursementLabel1)
                        .addGap(23, 23, 23)
                        .addGroup(recordContributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(submitContributionButton)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        organizationRepTabbedPane.addTab("Record Contribution", recordContributionPanel);

        recordDisbursementPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recordDisbursementPanelMouseEntered(evt);
            }
        });

        currentAppealDisbursementLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        currentAppealDisbursementLabel.setText("Current Appeals of");

        appealListDisbursement.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(appealListDisbursement);

        recordDisbursementLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        recordDisbursementLabel.setText("Record Disbursement");

        contributionListDisbursement.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(contributionListDisbursement);

        listContributionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listContributionLabel.setText("List of Contribution ");

        cashAmountLabel.setText("Cash amount");

        goodDisbursedLabel.setText("Good Disbursed");

        recordDisbursementButton.setText("Record !");
        recordDisbursementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordDisbursementButtonActionPerformed(evt);
            }
        });

        applicantListDisbursement.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(applicantListDisbursement);

        listContributionLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listContributionLabel1.setText("List of Applicant");

        listOfAppealLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listOfAppealLabel.setText("List of Appeal");

        javax.swing.GroupLayout recordDisbursementPanelLayout = new javax.swing.GroupLayout(recordDisbursementPanel);
        recordDisbursementPanel.setLayout(recordDisbursementPanelLayout);
        recordDisbursementPanelLayout.setHorizontalGroup(
            recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordDisbursementPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordDisbursementPanelLayout.createSequentialGroup()
                        .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(recordDisbursementPanelLayout.createSequentialGroup()
                                .addComponent(recordDisbursementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addComponent(listOfAppealLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordDisbursementPanelLayout.createSequentialGroup()
                                .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cashAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cashAmountLabel))
                                .addGap(35, 35, 35)
                                .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(recordDisbursementPanelLayout.createSequentialGroup()
                                        .addComponent(goodDisbursedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(recordDisbursementPanelLayout.createSequentialGroup()
                                        .addComponent(goodDisbursedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(recordDisbursementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(recordDisbursementPanelLayout.createSequentialGroup()
                        .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listContributionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listContributionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(currentAppealDisbursementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56))))
        );
        recordDisbursementPanelLayout.setVerticalGroup(
            recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordDisbursementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordDisbursementPanelLayout.createSequentialGroup()
                        .addComponent(recordDisbursementLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listContributionLabel1)
                            .addComponent(listContributionLabel)))
                    .addGroup(recordDisbursementPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(listOfAppealLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentAppealDisbursementLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashAmountLabel)
                    .addComponent(goodDisbursedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recordDisbursementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goodDisbursedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recordDisbursementButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        organizationRepTabbedPane.addTab("Record Disbursement", recordDisbursementPanel);

        applicantFullNameLabel.setText("Fullname :");

        applicantEmailLabel.setText("Email :");

        applicantMobileNoLabel.setText("Mobile No :");

        registerApplicantLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerApplicantLabel.setText("Register Applicant");

        applicantAddressLabel.setText("Address :");

        applicantHouseHoldIncomeLabel.setText("Household Income :");

        registerApplicantButton.setText("Register !");
        registerApplicantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerApplicantButtonActionPerformed(evt);
            }
        });

        titleOrganizationRegisterApplicantLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        titleOrganizationRegisterApplicantLabel.setText("Organization");

        infoOrganizationRegisterApplicantLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        infoOrganizationRegisterApplicantLabel.setText("detailed info organization");

        javax.swing.GroupLayout registerApplicantPanelLayout = new javax.swing.GroupLayout(registerApplicantPanel);
        registerApplicantPanel.setLayout(registerApplicantPanelLayout);
        registerApplicantPanelLayout.setHorizontalGroup(
            registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerApplicantPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerApplicantPanelLayout.createSequentialGroup()
                        .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerApplicantPanelLayout.createSequentialGroup()
                                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(applicantEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(applicantFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(applicantEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(applicantFullnameTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(registerApplicantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(registerApplicantPanelLayout.createSequentialGroup()
                                    .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerApplicantPanelLayout.createSequentialGroup()
                                            .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(applicantAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(applicantMobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(46, 46, 46))
                                        .addGroup(registerApplicantPanelLayout.createSequentialGroup()
                                            .addComponent(applicantHouseHoldIncomeLabel)
                                            .addGap(39, 39, 39)))
                                    .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(applicantHouseholdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                        .addComponent(applicantMobileNoTextField)
                                        .addComponent(applicantAddressTextField)))))
                        .addGap(0, 144, Short.MAX_VALUE))
                    .addGroup(registerApplicantPanelLayout.createSequentialGroup()
                        .addComponent(registerApplicantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerApplicantPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleOrganizationRegisterApplicantLabel)
                    .addComponent(infoOrganizationRegisterApplicantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        registerApplicantPanelLayout.setVerticalGroup(
            registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerApplicantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleOrganizationRegisterApplicantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerApplicantLabel)
                    .addComponent(infoOrganizationRegisterApplicantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applicantFullnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applicantFullNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applicantEmailLabel)
                    .addComponent(applicantEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applicantMobileNoLabel)
                    .addComponent(applicantMobileNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applicantAddressLabel)
                    .addComponent(applicantAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applicantHouseHoldIncomeLabel)
                    .addComponent(applicantHouseholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerApplicantButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        organizationRepTabbedPane.addTab("Register Applicant", registerApplicantPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(organizationRepTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(organizationRepTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // This method loads data related to appeals into the listModelAppeal.
public void LoadDataAppeal() {
    // Remove all existing elements from the listModelAppeal.
    listModelAppeal.removeAllElements();
    
    // Iterate through the list of appeals.
    for (int i = 0; i < appeals.size(); i++) {
        // Check if the appeal is marked as the current appeal.
        if (appeals.get(i).isCurrentAppeal()) {
            // Add the appeal ID to the listModelAppeal.
            listModelAppeal.addElement(appeals.get(i).getAppealID());
        }
    }
}

// This method loads data related to contributions into the listModelContribution.
public void LoadDataContribution() {
    // Remove all existing elements from the listModelContribution.
    listModelContribution.removeAllElements();
    
    // Get the selected index from contributionListDisbursement.
    int selectedIndex = contributionListDisbursement.getSelectedIndex();
    
    // Find the corresponding appeal based on the selected index in listModelAppeal.
    Appeal appeal = organization.findAppeal(listModelAppeal.getElementAt(selectedIndex + 1).toString());
    
    // Get the contributions associated with the selected appeal.
    ArrayList<Contribution> contributions = appeal.getContributions();
    
    // Iterate through the contributions and add their IDs to listModelContribution.
    for (int i = 0; i < contributions.size(); i++) {
        listModelContribution.addElement(contributions.get(i).getContributionID());
    }
}

    
    public void LoadDataContribution(Appeal appeal){
        listModelContribution.removeAllElements();
        ArrayList<Contribution> contribution = appeal.getContributions();
        for (int i = 0; i < contribution.size(); i++){
           listModelContribution.addElement(contribution.get(i).getContributionID());
        }
    }
    
    public void LoadDataApplicant(){
        listModelApplicant.removeAllElements();
        ArrayList<Applicant> applicant = organization.getApplicants();
        for (int i = 0; i < applicant.size(); i++){
            listModelApplicant.addElement(applicant.get(i).getIDNo());
        }
    }
    
    private void organizeAidAppealTabbedPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizeAidAppealTabbedPaneButtonActionPerformed
        // TODO add your handling code here:
          int selectedIndex = organizationRepTabbedPane.getSelectedIndex();
          int newIndex = (selectedIndex + 1) % organizationRepTabbedPane.getTabCount(); // Switch to the next tab in a circular manner
          organizationRepTabbedPane.setSelectedIndex(newIndex); 
    }//GEN-LAST:event_organizeAidAppealTabbedPaneButtonActionPerformed

    private void recordContributtionTabbedPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordContributtionTabbedPaneButtonActionPerformed
        // TODO add your handling code here:
            int selectedIndex = organizationRepTabbedPane.getSelectedIndex();
            int newIndex = (selectedIndex + 2) % organizationRepTabbedPane.getTabCount(); // Switch to the next tab in a circular manner
            organizationRepTabbedPane.setSelectedIndex(newIndex); 
    }//GEN-LAST:event_recordContributtionTabbedPaneButtonActionPerformed

    private void recordDisbursementTabbedPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordDisbursementTabbedPaneButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = organizationRepTabbedPane.getSelectedIndex();
        int newIndex = (selectedIndex + 3) % organizationRepTabbedPane.getTabCount(); // Switch to the next tab in a circular manner
        organizationRepTabbedPane.setSelectedIndex(newIndex); 
    }//GEN-LAST:event_recordDisbursementTabbedPaneButtonActionPerformed

    private void registerApplicantTabbedPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerApplicantTabbedPaneButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = organizationRepTabbedPane.getSelectedIndex();
        int newIndex = (selectedIndex + 4) % organizationRepTabbedPane.getTabCount(); // Switch to the next tab in a circular manner
        organizationRepTabbedPane.setSelectedIndex(newIndex); 
    }//GEN-LAST:event_registerApplicantTabbedPaneButtonActionPerformed

    private void organizeAidAppealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizeAidAppealButtonActionPerformed
        if (!toDateTextField.getText().equals("") && !fromDateTextField.getText().equals("") && !descriptionTextArea.getText().equals("")){
            HELPAidConsole.organizedAidAppeal(orgRep, fromDateTextField.getText(), toDateTextField.getText(), descriptionTextArea.getText());
        }
        LoadDataAppeal();
    }//GEN-LAST:event_organizeAidAppealButtonActionPerformed

    private void submitContributionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitContributionButtonActionPerformed
        // TODO add your handling code here:
        LoadDataAppeal();
        double amount = Double.parseDouble(amountTextField.getText());
        double estimatedValue = Double.parseDouble(estimatedValueTextField.getText());
        String appealID = listModelAppeal.getElementAt(appealListContribution.getSelectedIndex() + 1).toString();
        if (amountTextField.getText() != "" &&
            paymentChannelTextField.getText() != "" &&
            referenceNoTextField.getText() != "" &&
            descriptionTextArea.getText() != ""){
             HELPAidConsole.recordContribution(orgRep,
                     paymentChannelTextField.getText(),
                     referenceNoTextField.getText(),
                     appealID,
                     amount, 
                     contributionTypeComboBox.getSelectedItem().toString(), 
                     estimatedValue, descriptionTextArea.getText());
        }else {
            JOptionPane.showMessageDialog(null, "Tolong isi data terlebih dahulu");        }
    }//GEN-LAST:event_submitContributionButtonActionPerformed

    private void recordDisbursementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordDisbursementButtonActionPerformed
    LoadDataAppeal();
    LoadDataApplicant();
    Appeal appeal = appeals.get(appealListDisbursement.getSelectedIndex());
    String applicantID = listModelApplicant.getElementAt(appealListContribution.getSelectedIndex()).toString();
    double cashAmount = Double.parseDouble( cashAmountTextField.getText());
    double goodDisbursed = Double.parseDouble(goodDisbursedTextField.getText());
    LoadDataContribution(appeal);
    if (!"".equals(cashAmountTextField.getText()) && goodDisbursedTextField.getText() != null) {
        HELPAidConsole.recordDisbursement(orgRep, appeal.getAppealID(),applicantID ,cashAmount,goodDisbursed );
        }
    }//GEN-LAST:event_recordDisbursementButtonActionPerformed

    private void recordDisbursementPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordDisbursementPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_recordDisbursementPanelMouseEntered

    private void registerApplicantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerApplicantButtonActionPerformed
        // TODO add your handling code here:
        double houseHoldIncome = Integer.parseInt(applicantHouseholdTextField.getText());
        if(!applicantFullnameTextField.equals("")&&
           !applicantEmailTextField.equals("")&&
           !applicantHouseholdTextField.equals("")&&
           !applicantMobileNoTextField.equals("")&&
           !applicantAddressTextField.equals("")){
            HELPAidConsole.registerApplicant(organization,
                    applicantFullnameTextField.getText(),
                    applicantEmailTextField.getText(),
                    applicantMobileNoTextField.getText(),
                    applicantAddressTextField.getText(),
                    houseHoldIncome);
        }else {
            JOptionPane.showMessageDialog(null, "Tolong isi data terlebih dahulu");
        }
        LoadDataApplicant();
    }//GEN-LAST:event_registerApplicantButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganizationalRepresentativePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganizationalRepresentativePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganizationalRepresentativePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganizationalRepresentativePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganizationalRepresentativePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTextField;
    private javax.swing.JLabel appealDescriptionLabel;
    private javax.swing.JLabel appealFromDateLabel;
    private javax.swing.JList<String> appealListContribution;
    private javax.swing.JList<String> appealListDisbursement;
    private javax.swing.JLabel appealToDateLabel;
    private javax.swing.JLabel applicantAddressLabel;
    private javax.swing.JTextField applicantAddressTextField;
    private javax.swing.JLabel applicantEmailLabel;
    private javax.swing.JTextField applicantEmailTextField;
    private javax.swing.JLabel applicantFullNameLabel;
    private javax.swing.JTextField applicantFullnameTextField;
    private javax.swing.JLabel applicantHouseHoldIncomeLabel;
    private javax.swing.JTextField applicantHouseholdTextField;
    private javax.swing.JList<String> applicantListDisbursement;
    private javax.swing.JLabel applicantMobileNoLabel;
    private javax.swing.JTextField applicantMobileNoTextField;
    private javax.swing.JLabel cashAmountLabel;
    private javax.swing.JTextField cashAmountTextField;
    private javax.swing.JList<String> contributionListDisbursement;
    private javax.swing.JComboBox<String> contributionTypeComboBox;
    private javax.swing.JLabel contributionTypeLabel;
    private javax.swing.JLabel currentAppealDisbursementLabel;
    private javax.swing.JLabel currentAppealDisbursementLabel1;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel estimatedValueLabel;
    private javax.swing.JTextField estimatedValueTextField;
    private javax.swing.JTextField fromDateTextField;
    private javax.swing.JLabel goodDisbursedLabel;
    private javax.swing.JTextField goodDisbursedTextField;
    private javax.swing.JLabel infoOrganizationRegisterApplicantLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel listContributionLabel;
    private javax.swing.JLabel listContributionLabel1;
    private javax.swing.JLabel listOfAppealLabel;
    private javax.swing.JLabel orgRepWelcomePageLabel;
    private javax.swing.JTabbedPane organizationRepTabbedPane;
    private javax.swing.JButton organizeAidAppealButton;
    private javax.swing.JLabel organizeAidAppealLabel;
    private javax.swing.JLabel organizeAidAppealLabel1;
    private javax.swing.JPanel organizeAidAppealPanel;
    private javax.swing.JButton organizeAidAppealTabbedPaneButton;
    private javax.swing.JLabel paymentChannelLabel;
    private javax.swing.JTextField paymentChannelTextField;
    private javax.swing.JLabel recordContributionLabel;
    private javax.swing.JPanel recordContributionPanel;
    private javax.swing.JButton recordContributtionTabbedPaneButton;
    private javax.swing.JButton recordDisbursementButton;
    private javax.swing.JLabel recordDisbursementLabel;
    private javax.swing.JPanel recordDisbursementPanel;
    private javax.swing.JButton recordDisbursementTabbedPaneButton;
    private javax.swing.JLabel referenceNoLabel;
    private javax.swing.JTextField referenceNoTextField;
    private javax.swing.JButton registerApplicantButton;
    private javax.swing.JLabel registerApplicantLabel;
    private javax.swing.JPanel registerApplicantPanel;
    private javax.swing.JButton registerApplicantTabbedPaneButton;
    private javax.swing.JButton submitContributionButton;
    private javax.swing.JLabel titleOrganizationRegisterApplicantLabel;
    private javax.swing.JTextField toDateTextField;
    private javax.swing.JPanel welcomePagePanel;
    // End of variables declaration//GEN-END:variables
}
