/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Admin;

import controller.HELPAidConsole;
import static controller.HELPAidConsole.loginUser;
import controller.User;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;


public class AdminPage extends javax.swing.JFrame {
    
    DefaultListModel listModel = new DefaultListModel(); // Using list model for JList display
    ArrayList<User> users = new ArrayList<>(); // user arraylist untuk menampung data user

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
       initComponents();
       adminWelcomeLabel.setText("Welcome, " + loginUser.getFullname() + 
			" [Administrator]"); // untuk menampilkan data User yang logged in
       users = HELPAidConsole.getAllUsers(); // Untuk mengambil data seluruh pengguna
       updateComboBox(); // untuk mengupdate value yang ada di combobox
       loadAllDataUser(); // untuk mengupdate value yang ada di data user
       listUser.setModel(listModel); // untuk set listUser dengan model listModel
       organizationRepAddedOrgLabel.setText(""); //menghapus text di label
       organizationIDComboBox.setSelectedItem(""); //menghapus text di label
       DisplayPasswordUser.setText(""); //menghapus text di label
       DisplayEmailUser.setText(""); //menghapus text di label
       DisplayMobilePhoneUser.setText(""); //menghapus text di label
       DisplayNameUser.setText(""); //menghapus text di label
    }
    
   // This method is responsible for loading all user data into a graphical user interface component.
public void loadAllDataUser() {
    // Remove all existing elements from the list model.
    listModel.removeAllElements();

    // Iterate through the list of users.
    for (int i = 0; i < users.size(); i++) {
        // Add each user's full name to the list model.
        listModel.addElement(users.get(i).getFullname());
    }
}
    
  // This method updates the contents of a JComboBox with organization names.
public void updateComboBox() {
    // Create a new DefaultComboBoxModel using the organization names obtained from HELPAidConsole.
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(HELPAidConsole.getOrganizationName().toArray(new String[0]));

    // Set the newly created ComboBoxModel as the model for the organizationIDComboBox.
    organizationIDComboBox.setModel(comboBoxModel);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayAllUserTabbedPane = new javax.swing.JTabbedPane();
        AdminWelcomePageTabbedPane = new javax.swing.JPanel();
        adminWelcomeLabel = new javax.swing.JLabel();
        CreateOrganizationTabbedPaneButton = new javax.swing.JButton();
        CreateOrganizationRepTabbedPaneButton = new javax.swing.JButton();
        DisplayAllUserTabbedPaneButton = new javax.swing.JButton();
        AdminCreateOrganizationPageTabbedPane = new javax.swing.JPanel();
        OrganizationNameTextField = new javax.swing.JTextField();
        OrganizationAddressTextField = new javax.swing.JTextField();
        OrganizationNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CreateOrganizationButton = new javax.swing.JButton();
        AdminCreateOrganizationRepresentativePageTabbedPane = new javax.swing.JPanel();
        CreateOrganizationRepTitleLabel = new javax.swing.JLabel();
        FullNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        mobilePhoneTextField = new javax.swing.JTextField();
        jobPositionTextField = new javax.swing.JTextField();
        organizationIDComboBox = new javax.swing.JComboBox<>();
        organizationIDLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        mobilePhoneLabel = new javax.swing.JLabel();
        jobPositionLabel = new javax.swing.JLabel();
        CreateOrganizationRepButton = new javax.swing.JButton();
        addingRepresentativeForLabel = new javax.swing.JLabel();
        organizationRepAddedOrgLabel = new javax.swing.JLabel();
        AdminDisplayAllUserPageTabbedPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUser = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        UserPasswordLabel = new javax.swing.JLabel();
        UserMobilePhoneLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        DisplayNameUser = new javax.swing.JLabel();
        DisplayPasswordUser = new javax.swing.JLabel();
        DisplayMobilePhoneUser = new javax.swing.JLabel();
        DisplayEmailUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminWelcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adminWelcomeLabel.setText("Welcome Page");

        CreateOrganizationTabbedPaneButton.setText("Create Organization");
        CreateOrganizationTabbedPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateOrganizationTabbedPaneButtonActionPerformed(evt);
            }
        });

        CreateOrganizationRepTabbedPaneButton.setText("Create Organization Representative");
        CreateOrganizationRepTabbedPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateOrganizationRepTabbedPaneButtonActionPerformed(evt);
            }
        });

        DisplayAllUserTabbedPaneButton.setText("Display All User");
        DisplayAllUserTabbedPaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllUserTabbedPaneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminWelcomePageTabbedPaneLayout = new javax.swing.GroupLayout(AdminWelcomePageTabbedPane);
        AdminWelcomePageTabbedPane.setLayout(AdminWelcomePageTabbedPaneLayout);
        AdminWelcomePageTabbedPaneLayout.setHorizontalGroup(
            AdminWelcomePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminWelcomePageTabbedPaneLayout.createSequentialGroup()
                .addGroup(AdminWelcomePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminWelcomePageTabbedPaneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(adminWelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminWelcomePageTabbedPaneLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(AdminWelcomePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CreateOrganizationTabbedPaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreateOrganizationRepTabbedPaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(DisplayAllUserTabbedPaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        AdminWelcomePageTabbedPaneLayout.setVerticalGroup(
            AdminWelcomePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminWelcomePageTabbedPaneLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(adminWelcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(CreateOrganizationTabbedPaneButton)
                .addGap(18, 18, 18)
                .addComponent(CreateOrganizationRepTabbedPaneButton)
                .addGap(18, 18, 18)
                .addComponent(DisplayAllUserTabbedPaneButton)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        DisplayAllUserTabbedPane.addTab("Welcome Page", AdminWelcomePageTabbedPane);

        OrganizationNameLabel.setText("Organization Name :");

        jLabel1.setText("Organization Address :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Create New Organization");

        CreateOrganizationButton.setText("Create !");
        CreateOrganizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateOrganizationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminCreateOrganizationPageTabbedPaneLayout = new javax.swing.GroupLayout(AdminCreateOrganizationPageTabbedPane);
        AdminCreateOrganizationPageTabbedPane.setLayout(AdminCreateOrganizationPageTabbedPaneLayout);
        AdminCreateOrganizationPageTabbedPaneLayout.setHorizontalGroup(
            AdminCreateOrganizationPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminCreateOrganizationPageTabbedPaneLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(AdminCreateOrganizationPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CreateOrganizationButton)
                    .addGroup(AdminCreateOrganizationPageTabbedPaneLayout.createSequentialGroup()
                        .addGroup(AdminCreateOrganizationPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrganizationNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminCreateOrganizationPageTabbedPaneLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdminCreateOrganizationPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OrganizationNameTextField)
                            .addComponent(OrganizationAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54))
        );
        AdminCreateOrganizationPageTabbedPaneLayout.setVerticalGroup(
            AdminCreateOrganizationPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCreateOrganizationPageTabbedPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(AdminCreateOrganizationPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrganizationNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrganizationNameLabel))
                .addGap(26, 26, 26)
                .addGroup(AdminCreateOrganizationPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrganizationAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addComponent(CreateOrganizationButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        DisplayAllUserTabbedPane.addTab("Create Organization ", AdminCreateOrganizationPageTabbedPane);

        CreateOrganizationRepTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateOrganizationRepTitleLabel.setText("Create Organization Representative Page");

        organizationIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationIDComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationIDComboBoxActionPerformed(evt);
            }
        });

        organizationIDLabel.setText("Organization ID :");

        fullNameLabel.setText("Full Name        :");

        emailLabel.setText("Email               :");

        mobilePhoneLabel.setText("Mobile Phone :");

        jobPositionLabel.setText("Job Position    :");

        CreateOrganizationRepButton.setText("Create !");
        CreateOrganizationRepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateOrganizationRepButtonActionPerformed(evt);
            }
        });

        addingRepresentativeForLabel.setText("Adding Representative for :");

        organizationRepAddedOrgLabel.setText("jLabel4");

        javax.swing.GroupLayout AdminCreateOrganizationRepresentativePageTabbedPaneLayout = new javax.swing.GroupLayout(AdminCreateOrganizationRepresentativePageTabbedPane);
        AdminCreateOrganizationRepresentativePageTabbedPane.setLayout(AdminCreateOrganizationRepresentativePageTabbedPaneLayout);
        AdminCreateOrganizationRepresentativePageTabbedPaneLayout.setHorizontalGroup(
            AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createSequentialGroup()
                        .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mobilePhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jobPositionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(fullNameLabel))
                        .addGap(15, 15, 15)
                        .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jobPositionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobilePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FullNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(CreateOrganizationRepButton)
                        .addGap(41, 41, 41))
                    .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createSequentialGroup()
                        .addComponent(addingRepresentativeForLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organizationRepAddedOrgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(organizationIDLabel)
                        .addGap(9, 9, 9)
                        .addComponent(organizationIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreateOrganizationRepTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AdminCreateOrganizationRepresentativePageTabbedPaneLayout.setVerticalGroup(
            AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(CreateOrganizationRepTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationIDLabel)
                    .addComponent(organizationIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addingRepresentativeForLabel)
                    .addComponent(organizationRepAddedOrgLabel))
                .addGap(18, 18, 18)
                .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilePhoneLabel))
                .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jobPositionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jobPositionLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminCreateOrganizationRepresentativePageTabbedPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateOrganizationRepButton)
                        .addGap(50, 50, 50))))
        );

        DisplayAllUserTabbedPane.addTab("Create Organization Representative ", AdminCreateOrganizationRepresentativePageTabbedPane);

        listUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listUser);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Display All User");

        UserNameLabel.setText("Name              :");

        UserPasswordLabel.setText("Password        :");

        UserMobilePhoneLabel.setText("Mobile Phone :");

        EmailLabel.setText("Email               :");

        DisplayNameUser.setText("jLabel8");

        DisplayPasswordUser.setText("jLabel4");

        DisplayMobilePhoneUser.setText("jLabel4");

        DisplayEmailUser.setText("jLabel4");

        javax.swing.GroupLayout AdminDisplayAllUserPageTabbedPaneLayout = new javax.swing.GroupLayout(AdminDisplayAllUserPageTabbedPane);
        AdminDisplayAllUserPageTabbedPane.setLayout(AdminDisplayAllUserPageTabbedPaneLayout);
        AdminDisplayAllUserPageTabbedPaneLayout.setHorizontalGroup(
            AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UserPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UserMobilePhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UserNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(EmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DisplayNameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayPasswordUser, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(DisplayEmailUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayMobilePhoneUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        AdminDisplayAllUserPageTabbedPaneLayout.setVerticalGroup(
            AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminDisplayAllUserPageTabbedPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createSequentialGroup()
                        .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserNameLabel)
                            .addComponent(DisplayNameUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserPasswordLabel)
                            .addComponent(DisplayPasswordUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserMobilePhoneLabel)
                            .addComponent(DisplayMobilePhoneUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdminDisplayAllUserPageTabbedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailLabel)
                            .addComponent(DisplayEmailUser))))
                .addGap(27, 27, 27))
        );

        DisplayAllUserTabbedPane.addTab("Display All Users", AdminDisplayAllUserPageTabbedPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayAllUserTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayAllUserTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateOrganizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateOrganizationButtonActionPerformed
        
         // Check if both the OrganizationNameTextField and OrganizationAddressTextField are not null or empty.
    if (!OrganizationNameTextField.getText().equals(null) && !OrganizationAddressTextField.getText().equals(null)){
        // Call the createOrganization method in HELPAidConsole with the provided organization name and address.
        HELPAidConsole.createOrganization(OrganizationNameTextField.getText(), OrganizationAddressTextField.getText());

        // Update the content of the JComboBox after creating the organization.
        updateComboBox();

        // Clear the text fields after organization creation.
        OrganizationNameTextField.setText("");
        OrganizationAddressTextField.setText("");
    }
    }//GEN-LAST:event_CreateOrganizationButtonActionPerformed

    private void organizationIDComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationIDComboBoxActionPerformed
        // Get the selected organization ID from the JComboBox.
    String orgID = organizationIDComboBox.getSelectedItem().toString();

    // Set the text of organizationRepAddedOrgLabel to the organization name corresponding to the selected ID.
    organizationRepAddedOrgLabel.setText(HELPAidConsole.findOrgNameFromID(orgID));

    }//GEN-LAST:event_organizationIDComboBoxActionPerformed

    private void CreateOrganizationRepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateOrganizationRepButtonActionPerformed
        // Check if the required text fields are not null or empty.
    if (!FullNameTextField.getText().equals(null) && !emailTextField.getText().equals(null) && !mobilePhoneTextField.getText().equals(null)){
        // Call the createOrganizationRep method in HELPAidConsole with the provided information.
        HELPAidConsole.createOrganizationRep(
            organizationIDComboBox.getSelectedItem().toString(),
            FullNameTextField.getText(),
            emailTextField.getText(),
            mobilePhoneTextField.getText(),
            jobPositionTextField.getText()
        );

        // Load all user data into the GUI, presumably refreshing a user list.
        loadAllDataUser();

        // Clear the text fields after creating the organization representative.
        FullNameTextField.setText("");
        emailTextField.setText("");
        mobilePhoneTextField.setText("");
    }
    }//GEN-LAST:event_CreateOrganizationRepButtonActionPerformed

    private void listUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUserMouseClicked
        // Retrieve the selected user index from the listUser component.
    int selectedIndex = listUser.getSelectedIndex();

    // Set the display components with information from the selected user.
    DisplayNameUser.setText(users.get(selectedIndex).getFullname());
    DisplayEmailUser.setText(users.get(selectedIndex).getEmail());
    DisplayMobilePhoneUser.setText(users.get(selectedIndex).getMobileNo());
    DisplayPasswordUser.setText(users.get(selectedIndex).getPassword());

    }//GEN-LAST:event_listUserMouseClicked

    private void CreateOrganizationTabbedPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateOrganizationTabbedPaneButtonActionPerformed
                int selectedIndex = DisplayAllUserTabbedPane.getSelectedIndex();
                int newIndex = (selectedIndex + 1) % DisplayAllUserTabbedPane.getTabCount(); // Switch to the next tab in a circular manner
                DisplayAllUserTabbedPane.setSelectedIndex(newIndex);        // TODO add your handling code here:
    }//GEN-LAST:event_CreateOrganizationTabbedPaneButtonActionPerformed

    private void CreateOrganizationRepTabbedPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateOrganizationRepTabbedPaneButtonActionPerformed
                int selectedIndex = DisplayAllUserTabbedPane.getSelectedIndex();
                int newIndex = (selectedIndex + 2) % DisplayAllUserTabbedPane.getTabCount(); // Switch to the next tab in a circular manner
                DisplayAllUserTabbedPane.setSelectedIndex(newIndex);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_CreateOrganizationRepTabbedPaneButtonActionPerformed

    private void DisplayAllUserTabbedPaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllUserTabbedPaneButtonActionPerformed
                int selectedIndex = DisplayAllUserTabbedPane.getSelectedIndex();
                int newIndex = (selectedIndex + 3) % DisplayAllUserTabbedPane.getTabCount(); // Switch to the next tab in a circular manner
                DisplayAllUserTabbedPane.setSelectedIndex(newIndex);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayAllUserTabbedPaneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCreateOrganizationPageTabbedPane;
    private javax.swing.JPanel AdminCreateOrganizationRepresentativePageTabbedPane;
    private javax.swing.JPanel AdminDisplayAllUserPageTabbedPane;
    private javax.swing.JPanel AdminWelcomePageTabbedPane;
    private javax.swing.JButton CreateOrganizationButton;
    private javax.swing.JButton CreateOrganizationRepButton;
    private javax.swing.JButton CreateOrganizationRepTabbedPaneButton;
    private javax.swing.JLabel CreateOrganizationRepTitleLabel;
    private javax.swing.JButton CreateOrganizationTabbedPaneButton;
    private javax.swing.JTabbedPane DisplayAllUserTabbedPane;
    private javax.swing.JButton DisplayAllUserTabbedPaneButton;
    private javax.swing.JLabel DisplayEmailUser;
    private javax.swing.JLabel DisplayMobilePhoneUser;
    private javax.swing.JLabel DisplayNameUser;
    private javax.swing.JLabel DisplayPasswordUser;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField FullNameTextField;
    private javax.swing.JTextField OrganizationAddressTextField;
    private javax.swing.JLabel OrganizationNameLabel;
    private javax.swing.JTextField OrganizationNameTextField;
    private javax.swing.JLabel UserMobilePhoneLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JLabel UserPasswordLabel;
    private javax.swing.JLabel addingRepresentativeForLabel;
    private javax.swing.JLabel adminWelcomeLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jobPositionLabel;
    private javax.swing.JTextField jobPositionTextField;
    private javax.swing.JList<String> listUser;
    private javax.swing.JLabel mobilePhoneLabel;
    private javax.swing.JTextField mobilePhoneTextField;
    private javax.swing.JComboBox<String> organizationIDComboBox;
    private javax.swing.JLabel organizationIDLabel;
    private javax.swing.JLabel organizationRepAddedOrgLabel;
    // End of variables declaration//GEN-END:variables
}
